// <auto-generated />
namespace Capstone_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingtokentouserrtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingtokentouserrtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701131714244_Adding token to userr table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
