// <auto-generated />
namespace Capstone_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddelaysettingtouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddelaysettingtouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201701172358370_added delay setting to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
