// <auto-generated />
namespace Capstone_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateddatename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddatename));
        
        string IMigrationMetadata.Id
        {
            get { return "201701180823273_updated date name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
