// <auto-generated />
namespace Capstone_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedexpirationdatetomessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedexpirationdatetomessages));
        
        string IMigrationMetadata.Id
        {
            get { return "201701172058011_Added expiration date to messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
